# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d09d4dd501369abe3162d97c944a1a1f1766b3b6c7acb4a42893ade16ee2bd418166dab01accde9a4e6abd8518660e606b346d4150c61154968c4695d0669631

test:
  secret_key_base: fcd457884fef9abbbaa7201bd15c9abcdfc9944af83abdad9a8c16ff8971fd6a4e012b8c245e0be58be29bf3734755021570520017c373f5ad3d50fcf967d0f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
